/* eslint-disable @next/next/no-html-link-for-pages */
// pages/index.js(Homeページ)

// デフォルト設定コンポーネント
import React from 'react'                       
import Head from 'next/head'                                       
import { Inter } from 'next/font/google'         
import styles from '@/styles/Home.module.css'                         
// カスタム要素コンポーネント
import Layout from '../components/Layout' // Header2,Layout{child}main,Footer
import Hero from '../components/Hero'
import WorksBox from '../components/WorksBox'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>
      {/* <Head> ======================================================= */}
      <Head>
        <title>LumiKojo | PORTFOLIO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="google" content="notranslate" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      {/* <main> ======================================================= */}
      <div className='bg-white'>
        <Layout>
          <Hero />
          <WorksBox />
        </Layout>
      </div>
    </div>
  )
}