/* eslint-disable @next/next/no-html-link-for-pages */
// pages/index.js(Homeページ)

// デフォルト設定コンポーネント
import React from 'react'                       
import Head from 'next/head'                     
import Image from 'next/image'                   
import { Inter } from 'next/font/google'         
import styles from '@/styles/Home.module.css'    
import Link from 'next/link'                     
// カスタム要素コンポーネント
import Btn from '../components/Button/Btn'
import Layout from '../components/Layout'   // Header,Layout{child}main,Footer
import Hero from '../components/Hero'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
    {/* <Head> =========================================================== */}
      <Head>
        <title>LumiKojo | PORTFOLIO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="google" content="notranslate" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>

    {/* <Header,main,Footer><Layout{child}main detail> =================== */}
      <Layout>
        <div> {/* <Layout{children}> */}

          {/* Hero =================================================== */}
          <Hero />



          {/* 遷移ボタン =================================================== */}
          <div className='flex justify-center'>
            <Btn className="bg-slate-600"><Link href="/test2">テスト<span className='text-2xl'>2</span>へ</Link></Btn>
            <Btn className="bg-yellow-600"><Link href="/test5">テスト<span className='text-2xl'>5</span>へ</Link></Btn>
          </div>
          
          {/* Works =====================================================*/}
          <div className='mt-[52px]' id="works"> 
            <div className={styles.center} >
              <h2 className="text-8xl text-black italic">Works</h2>
            </div>
            {/* ギャラリー */}
            <div className='flex justify-center'>
            <div className={styles.grid}>


              {/* web01 _____________________________ */}
              <Link
                href="/works/web01"
                className={styles.card}
                rel="noopener noreferrer"
              >
                <div style={{ position: "relative", height: "20vh" }}>
                  <Image
                      className='h-5 w-full object-cover md:h-full md:w-12'
                      src="/img04.jpg"
                      alt="Hero img"
                      fill style={{ objectFit: "cover" }}
                      priority
                  />  
                </div>
                <h2>
                  Docs <span>-&gt;</span>
                </h2>
                <p>
                  Find in-depth information about Next.js features and&nbsp;API.
                </p>
              </Link>

              {/* web01 _____________________________ */}
              <Link
                href="/works/web01"
                className={styles.card}
                rel="noopener noreferrer"
              >
                <div style={{ position: "relative", height: "20vh" }}>
                  <Image
                      className='h-5 w-full object-cover md:h-full md:w-12'
                      src="/image01.jpg"
                      alt="Hero img"
                      fill style={{ objectFit: "cover" }}
                      priority
                  />  
                </div>
                <h2>
                  Docs <span>-&gt;</span>
                </h2>
                <p>
                  Find in-depth information about Next.js features and&nbsp;API.
                </p>
              </Link>

              {/* web01 _____________________________ */}
              <Link
                href="/works/web01"
                className={styles.card}
                rel="noopener noreferrer"
              >
                <div style={{ position: "relative", height: "20vh" }}>
                  <Image
                      className='h-5 w-full object-cover md:h-full md:w-12'
                      src="/image01.jpg"
                      alt="Hero img"
                      fill style={{ objectFit: "cover" }}
                      priority
                  />  
                </div>
                <h2>
                  Docs <span>-&gt;</span>
                </h2>
                <p>
                  Find in-depth information about Next.js features and&nbsp;API.
                </p>
              </Link>

              {/* web01 _____________________________ */}
              <Link
                href="/works/web01"
                className={styles.card}
                rel="noopener noreferrer"
              >
                <div style={{ position: "relative", height: "20vh" }}>
                  <Image
                      className='h-5 w-full object-cover md:h-full md:w-12'
                      src="/image01.jpg"
                      alt="Hero img"
                      fill style={{ objectFit: "cover" }}
                      priority
                  />  
                </div>
                <h2>
                  Docs <span>-&gt;</span>
                </h2>
                <p>
                  Find in-depth information about Next.js features and&nbsp;API.
                </p>
              </Link>

              {/* web01 _____________________________ */}
              <Link
                href="/works/web01"
                className={styles.card}
                rel="noopener noreferrer"
              >
                <div style={{ position: "relative", height: "20vh" }}>
                  <Image
                      className='h-5 w-full object-cover md:h-full md:w-12'
                      src="/image01.jpg"
                      alt="Hero img"
                      fill style={{ objectFit: "cover" }}
                      priority
                  />  
                </div>
                <h2>
                  Docs <span>-&gt;</span>
                </h2>
                <p>
                  Find in-depth information about Next.js features and&nbsp;API. 
                </p>
              </Link>
              </div>
            </div>
          </div>
          {/* Works ここまで =================================================*/}

        </div> {/* <Layout{child}>ここまで ===================================*/}
      </Layout>
    </>
  )
}
